server {
    listen 8443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/localhost.pem;
    ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

    # 1. Frontend: Serve Angular static files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Auth Service -> Spring Gateway
    location /auth {
        proxy_pass https://gateway:8089/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_verify off;
    }
    # 1. SPECIAL CASE: /products/add is strictly an Angular route, NEVER an API call
    location = /products/add {
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }
    # 3. Product Service -> Spring Gateway
    location /products {
        if ($http_accept ~* "text/html") {
            rewrite ^ /index.html last;
        }
        proxy_pass https://gateway:8089/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_verify off;
    }

    # 4. Media Service API -> Spring Gateway
    location /media {
        client_max_body_size 20M;
        proxy_pass https://gateway:8089/media;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_verify off;
    }

    # 5. Serve Uploaded Images -> Spring Gateway
    location /uploads {
        proxy_pass https://gateway:8089/uploads;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_verify off;
    }
}