server:
  port: 8081

spring:
  application:
    name: user_service

  data:
    mongodb:
      uri: mongodb://localhost:27017/buy01
      

    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 10m
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer