spring:
  application:
    name: product_service

  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  web:
    resources:
      static-locations:
        - file:uploads/

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: buy01.product_service.event.UserDeletedEvent

management:
  endpoints:
    web:
      exposure:
        include: health

media:
  service:
    url: http://localhost:8083