server:
  port: 8082

spring:
  application:
    name: product_service

  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db

management:
  endpoints:
    web:
      exposure:
        include: health